### ISSUE TITLE
bbcode 新增样式

### ISSUE THREAD

**Issue by lgc2333** [MeetWq/pil-utils#1]
https://github.com/lgc2333/nonebot-plugin-picmcstat#-%E4%BB%8B%E7%BB%8D

如果能加上 下划线、删除线和斜体 就更好了！

**Comment by MeetWq** [comment]
这些我不知道该怎么实现QAQ

**Comment by lgc2333** [comment]
下划线删除线可以改下char的draw_on函数？在画完char之后画条线
但是斜体我不知道怎么搞

**Comment by MeetWq** [comment]
有些字体是有斜体的，但中文只能靠伪斜体

**Comment by lgc2333** [comment]
还有bold在unifont里没用……不知道什么情况

**Comment by MeetWq** [comment]
> 还有bold在unifont里没用……不知道什么情况

unifont 有没有粗体字体？

**Comment by lgc2333** [comment]
> 

貌似好像没有，不知道是不是我没装
我在这里下载的
http://ftp.gnu.org/gnu/unifont/unifont-15.0.01/
只安装了 `unifont-15.0.01.ttf` 这一个字体

**Comment by MeetWq** [comment]
目前 下划线、删除线 加了

有些效果可能不如预期 [del]又不是不能用[/del]：
如果一行里面有大小不同大小的字，下划线会对不齐；
如果一行里面有不同字体或不同大小的字，删除线会对不齐

粗体和斜体目前还是得看有没有对应的字体，所以汉字目前基本没法斜体
但我试了一些网站上 bbcode 的效果，汉字是可以斜的，感觉之后还是得想想怎么手动实现

**Comment by lgc2333** [comment]
thanks!!

**Comment by lgc2333** [comment]
![V`1N17RV)~ Z$J14BY@ DBR](https://user-images.githubusercontent.com/59048777/229864821-3e17114e-f045-432d-9aec-1df904ce769e.PNG)

这里的字我都上了stroke，下划线被stroke盖住了……

能不能把线也上一下stroke（

**Comment by lgc2333** [comment]
any update? if no i'll close this issue
